version: "3.5"
services:
  webapp:
    container_name: webapp
    build:
      context: './php/'
      args:
        - PHP_V=${PHP_V}
    ports:
      - '8080:80'
    depends_on:
      - api
    volumes:
      - ./public/:/var/www/html/
    networks:
      default:
        ipv4_address: 172.18.1.9
  api:
    container_name: api
    build:
      context: './api/'
      args:
        - PHP_V=${PHP_V}
    volumes:
      - ./api/:/var/www/html/
    depends_on:
      - db
    ports:
      - "8090:80"
    networks:
      default:
        ipv4_address: 172.18.1.4
  db:
    container_name: mysqldb
    build:
      context: './mysql/'
      args:
        - MYSQL_V=${MYSQL_V}
    restart: always
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - data:/var/lib/mysql
    networks:
      default:
        ipv4_address: 172.18.1.6
    environment:
      MYSQL_ROOT_HOST: 172.18.1.5
      MYSQL_ROOT_PASSWORD: "${DB_ROOT_PASSWORD}"
      MYSQL_DATABASE: "${DB_DATABASE}"
      MYSQL_PASSWORD: "${DB_PASSWORD}"

  keyrock:
    image: fiware/idm
    container_name: fiware_keyrock
    hostname: keyrock
    networks:
      default:
        ipv4_address: 172.18.1.5
    depends_on:
      - db
    ports:
      - '3005:3005'
      - '443:443'
    environment:
      - DEBUG=idm:*
      - IDM_DB_HOST=db
      - IDM_HOST=https://localhost:3005
      - IDM_PORT=3005
      - IDM_DB_PASS=rootpassword
      - IDM_DB_USER=root
      - IDM_ADMIN_USER=admin
      - IDM_ADMIN_EMAIL=admin@test.com
      - IDM_ADMIN_PASS=nimda

  phpmyadmin:
    container_name: phpmyadmin
    image: phpmyadmin/phpmyadmin
    restart: always
    depends_on:
      - db
    ports:
      - '8000:80'
    networks:
      default:
        ipv4_address: 172.18.1.7
    environment:
      PMA_HOST: db
      MYSQL_ROOT_PASSWORD: rootpassword

networks:
  default:
    ipam:
      config:
        - subnet: 172.18.1.0/24
volumes:
  data:
